//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECommerceEntities : DbContext
    {
        public ECommerceEntities()
            : base("name=ECommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LogTable> LogTables { get; set; }
    
        public virtual ObjectResult<GetProductList_Result> GetProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductList_Result>("GetProductList");
        }
    
        public virtual ObjectResult<Get_OrdDetAdd_Result> Get_OrdDetAdd(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_OrdDetAdd_Result>("Get_OrdDetAdd", idParameter);
        }
    
        public virtual ObjectResult<Get_OrdDetAdd2_Result> Get_OrdDetAdd2(Nullable<int> orderDetID)
        {
            var orderDetIDParameter = orderDetID.HasValue ?
                new ObjectParameter("orderDetID", orderDetID) :
                new ObjectParameter("orderDetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_OrdDetAdd2_Result>("Get_OrdDetAdd2", orderDetIDParameter);
        }
    
        public virtual ObjectResult<Get_OrdDetAdd3_Result> Get_OrdDetAdd3(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_OrdDetAdd3_Result>("Get_OrdDetAdd3", idParameter);
        }
    
        public virtual ObjectResult<Get_OrdDetAddress_Result> Get_OrdDetAddress(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_OrdDetAddress_Result>("Get_OrdDetAddress", idParameter);
        }
    }
}
